<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container4sxTyT8\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container4sxTyT8/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container4sxTyT8.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container4sxTyT8\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container4sxTyT8\App_KernelDevDebugContainer([
    'container.build_hash' => '4sxTyT8',
    'container.build_id' => '5e135228',
    'container.build_time' => 1624622671,
], __DIR__.\DIRECTORY_SEPARATOR.'Container4sxTyT8');
