<?php

namespace Container4sxTyT8;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCreateUserService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Core\User\Command\CreateUser' shared autowired service.
     *
     * @return \App\Core\User\Command\CreateUser
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Core/User/Command/CreateUser.php';

        $container->privates['App\\Core\\User\\Command\\CreateUser'] = $instance = new \App\Core\User\Command\CreateUser(($container->privates['App\\Core\\User\\Repository\\UserRepository'] ?? $container->load('getUserRepositoryService')));

        $instance->setName('app:core:create-user');

        return $instance;
    }
}
